version: "3.7"
services:
  pocketbase:
    build: 
      context: ./apps/pocketbase
      args: 
        - VERSION=0.19.4
    image: 445044180652.dkr.ecr.us-west-1.amazonaws.com/cureeat-pocketbase
    container_name: cureeat-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /srv/pocketbase:/srv/pocketbase
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  webapp:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      additional_contexts:
        monorepo: ./
      args:
        - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
        - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
        - KROGER_SECRET=${KROGER_SECRET}
        - PUBLIC_KROGER_CLIENT_ID=${PUBLIC_KROGER_CLIENT_ID}
    image: 445044180652.dkr.ecr.us-west-1.amazonaws.com/cureeat-webapp
    container_name: cureeat-webapp
    restart: unless-stopped
    ports:
      - "3000:3000"