version: "3.7"
services:
  pocketbase:
    build: 
      context: ./apps/pocketbase
      args: 
        - VERSION=0.19.4
    image: cureeat-pocketbase-dev
    container_name: cureeat-pocketbase-dev
    restart: unless-stopped
    command: --debug
    ports:
      - "8090:8090"
    volumes:
      - type: bind
        source: ./apps/pocketbase
        target: /srv/pocketbase
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  webapp:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
      additional_contexts:
        monorepo: ./
    image: cureeat-web-dev
    volumes:
      - type: bind
        source: ./apps/web
        target: /home/cureeat/apps/web
    container_name: cureeat-web-dev
    restart: unless-stopped
    ports:
      - "5173:5173"