version: "3.7"
services:
  pocketbase:
    build: 
      context: ./apps/pocketbase
      args: 
        - VERSION=0.19.4
    container_name: cure-eat-pocketbase-prod
    restart: unless-stopped
    command: --debug
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_migrations:/pb_migrations
      - ./pb_hooks:/pb_hooks
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  webapp:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.prod
    container_name: cure-eat-webapp-prod
    restart: unless-stopped
    ports:
      - "3000:3000"